name: "aml2026-group-15"
channels:
  - conda-forge
  - pytorch
  - nvidia
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - tmux
  - ncurses>=6.4
  - scikit-learn
  - pandas
  - seaborn
  - matplotlib
  - jupyterlab
  - tqdm
  - pip:
      - transformers[torch]
      - rank_bm25
      - accelerate
      - datasets
